services:
  db:
    image: postgres:16
    container_name: tubu-dev-db
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      TZ: "Asia/Tokyo"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "tubu_dev"

volumes:
  db_data:
