services:
  bot:
    container_name: tubu-bot
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BOT_VERSION: "development-build"
    env_file:
      - .env
    restart: unless-stopped
