version: "3"

vars:
  METADATA_PATH: github.com/aqyuki/tubu/packages/metadata
  GO_VERSION:
    sh: go version | awk '{print $3}' | sed 's/go//'
  BUILD_DATE:
    sh: date -u '+%Y-%m-%dT%H:%M:%SZ'
  COMMIT_HASH:
    sh: git rev-parse --short HEAD

tasks:
  build:
    desc: "Botをビルドします．"
    cmds:
      - |
        go build -ldflags="-s -w \
        -X '{{.METADATA_PATH}}.GoVersion={{.GO_VERSION}}' \
        -X '{{.METADATA_PATH}}.BuildDate={{.BUILD_DATE}}' \
        -X '{{.METADATA_PATH}}.CommitHash={{.COMMIT_HASH}}'" \
        -o bin/bot main.go
  start:
    desc: "Botをビルドし，起動します."
    cmds:
      - task: build
      - ./bin/bot
  test:
    desc: "テストを実行します．"
    cmds:
      - go test -v -shuffle=on -short ./...
  full-test:
    desc: "全てのテストを実行します．"
    cmds:
      - go test -v -shuffle=on ./...
  coverage:
    desc: "カバレッジを測定します．"
    cmds:
      - go test  -v -shuffle=on  -coverprofile=coverage.out ./...
