name: ✨機能関係のリクエスト
description: 新機能の追加や，既存の機能の改善に関するリクエスト用
title: "✨ "
labels:
  - ":sparkles: feat"

body:
  - type: textarea
    id: description
    attributes:
      label: 機能の説明
      description: 追加や改善を希望する機能について具体的に説明してください
