name: Go
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          TZ: "Asia/Tokyo"
          POSTGRES_USER: "user"
          POSTGRES_PASSWORD: "password"
          POSTGRES_DB: "tubu_dev"
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Run tests
        env:
          DATABASE_URL: postgres://user:password@localhost:5432/tubu_dev?sslmode=disable
        run: go test -v -coverprofile=coverage.out -shuffle=$GITHUB_RUN_ID ./...
      - uses: k1LoW/octocov-action@v1
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Build
        run: go build -v ./...
  vet:
    name: vet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Vet
        run: go vet ./...
